const activeRoutes = [
  ['/customer/app_supplier', '供应商'],
  ['/customer/app_customer_income', '收入明细'],
  ['/customer/app_consultant', '康养顾问'],
  ['/customer/app_customer', '客户资料'],
  ['/attachments', '附件'],
  ['/order/app_goods_order', '商品订单'],
  ['/order/app_goods_order_after', '订单商品售后'],
  ['/order/app_express', '快递公司'],
  ['/order/app_user_address', '用户地址'],
  ['/goods/app_goods', '商品信息'],
  ['/goods/app_goods_category', '商品分类'],
  ['/goods/app_goods_cart', '用户购物车'],
  ['/activity/app_activity_category', '活动分类'],
  ['/activity/app_user_gold_log', '金币记录'],
  ['/activity/app_goods_coupon', '商品优惠券'],
  ['/activity/app_goods_coupon_got', '优惠券领取记录'],
  ['/article/app_article', '图文内容'],
  ['/article/app_article_category', '内容分类'],
  ['/article/app_single_page', '单页文章'],
  ['/shop/app_config', '商城配置'],
  ['/shop/app_ad_position', '广告管理'],
  ['/shop/app_ad_content', '广告内容'],
  ['/promotion/app_user_card', '用户会员卡'],
  ['/promotion/app_card', '会员卡设置'],
  ['/promotion/app_user_inviter', '邀请记录'],
  ['/system/app_area', '行政区域'],
  ['/system/user', '用户管理'],
  ['/system/role', '角色管理'],
  ['/system/menu', '菜单管理'],
  ['/system/dept', '组织架构'],
  ['/system/post', '岗位管理'],
  ['/system/dict', '字典管理'],
  ['/system/config', '参数设置'],
  ['/system/notice', '通知公告'],
  ['/system/log/operlog', '操作日志'],
  ['/system/log/logininfor', '登录日志'],
  ['/tool/build', '表单构建'],
  ['/tool/gen', '代码生成'],
  ['/tool/swagger', '系统接口'],
  ['/monitor/online', '在线用户'],
  ['/monitor/job', '定时任务'],
  ['/monitor/druid', '数据监控'],
  ['/monitor/server', '服务监控'],
  ['/monitor/cache', '缓存监控'],
  ['/monitor/cacheList', '缓存列表']
]

const unavailableRoutes = [
  ['/order/app_goods_comment', '订单商品评价', 'system/app_goods_comment/index'],
  ['/goods/app_goods_sku', '商品属性', 'system/app_goods_sku/index'],
  ['/goods/app_goods_collect', '商品收藏', 'system/app_goods_collect/index'],
  ['/activity/app_activity', '活动', 'system/app_activity/index'],
  ['/activity/app_activity_order', '活动预约', 'system/app_activity_order/index']
]

module.exports = { activeRoutes, unavailableRoutes }
